<?php
use Magento\Framework\App\Action\Action;

if($block->isPage('catalog_category_view')){$relateds = $block->getRelated(0);}
elseif($block->isPage('cms_index_index')){$relateds = $block->getRelated(1);}
elseif($block->isPage('checkout_cart_index')){$relateds = $block->getRelated(2);}
elseif($block->isPage('catalog_product_view')){$relateds = $block->getRelated(3);}
foreach ($relateds as $related){}
$showCart     = $related->getCart();
$showReview   = $related->getReview();
$showCompare  = $related->getCompare();
$showWishlist = $related->getWishlist();
$stringIds    = $related->getProducts();
$arrIds       = explode(",",$stringIds);
$items        = $block->getProductCollection($arrIds);
$image        = 'new_products_content_widget_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<div class="product-slider-block block widget block-products-list">
  <h2 class="product-slider-title"><?php echo $related->getTitle(); ?></h2>
</div>

<div class="block widget block-products-list grid">
  <div class="block-content">
    <div class="products-grid grid">
      <?php if($related->getSlider() == 1): ?>
        <ol class="product-items widget-viewed-grid regular slider">
          <?php else: ?>
            <ol class="product-items widget-viewed-grid">
            <?php endif; ?>
            <?php foreach ($items as $_item): ?>
              <li class="product-item">
                <div class="product-item-info">
                  <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                    <?= $block->getImage($_item, $image)->toHtml() ?>
                  </a>
                  <div class="product-item-details">
                    <strong class="product-item-name">
                      <a title="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" href="<?php echo $_item->getProductUrl(); ?>" class="product-item-link"><?= $_item->getName(); ?></a>
                    </strong>
                    <?php if($showReview): ?>
                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <?php endif; ?>
                    <?= $block->getProductPrice($_item) ?>
                    <?php if ($_item->isAvailable()) :?>
                      <?= $block->getProductDetailsHtml($_item) ?>
                    <?php endif; ?>

                    <div class="product-item-inner">
                      <div class="product-item-actions">
                        <div class="actions-primary">
                        <?php if($showCart): ?>
                          <?php if ($_item->isSaleable()) : ?>
                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                              <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                              <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                              <?= $block->getBlockHtml('formkey') ?>
                              <button type="submit"
                              title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                              class="action tocart primary">
                              <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                            </button>
                          </form>
                          <?php else : ?>
                            <?php if ($_item->getIsSalable()) : ?>
                              <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                              <?php else : ?>
                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                              <?php endif; ?>
                            <?php endif; ?>
                          <?php endif; ?>
                          </div>
                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                      <?php if($showWishlist): ?>
                        <a href="#" data-post='<?= /* @noEscape */ $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist">
                          <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                        </a>
                      <?php endif; ?>
                      <?php if($showCompare): ?>
                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <a href="#" class="action tocompare"
                        data-post='<?= /** @noEscape */ $compareHelper->getPostDataParams($_item); ?>'
                        data-role="add-to-links"
                        title="<?= /** @noEscape */ $block->escapeHtml(__('Add to Compare')) ?>">
                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                      </a>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      <?php endforeach; ?>
    </ol>
  </div>
</div>
</div>
<script type="text/x-magento-init">
{
  "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
        "bindSubmit": true
      }
    },

  "*": {
    "Magento_Ui/js/core/app": {
      "components": {
        "wishlist": {
        "component": "Magento_Wishlist/js/view/wishlist"
        }
      }
    },
    "magepowRelated": {
    }
  }
}
</script>