<?php
use Magento\Framework\App\Action\Action;
if($block->isPage('catalog_category_view')){$relateds = $block->getRelated(0);}
elseif($block->isPage('cms_index_index')){$relateds = $block->getRelated(1);}
elseif($block->isPage('checkout_cart_index')){$relateds = $block->getRelated(2);}
elseif($block->isPage('catalog_product_view')){$relateds = $block->getRelated(3);}
foreach ($relateds as $related){}
	$stringIds = $related->getProducts();
  $arrIds = explode(",",$stringIds);
  $items = $block->getProductCollection($arrIds);?>
<div class="product-slider-block block widget block-products-list">
  <h2 class="product-slider-title"><?php echo $related->getTitle(); ?></h2>
</div>

<div class="block widget block-products-list grid">
  <div class="block-content">
    <div class="products-grid grid">
      <?php if($related->getSlider() == 1): ?>
        <ol class="product-items widget-viewed-grid regular slider">
          <?php else: ?>
            <ol class="product-items widget-viewed-grid">
            <?php endif; ?>
            <?php foreach ($items as $_item): ?>
              <?php $_imageHelper = $this->helper('Magento\Catalog\Helper\Image');
              $imageUrl = $_imageHelper->init($_item, 'product_base_image')
              ->constrainOnly(TRUE)
              ->keepAspectRatio(TRUE)
              ->keepTransparency(TRUE)
              ->keepFrame(TRUE)
              ->resize(240, 300)->getUrl();?>
                  <li class="product-item">
                    <div class="product-item-info">
                      <a href="<?php echo $_item->getProductUrl(); ?>" class="product-item-photo">
                        <span class="product-image-container" style="width:240px;">
                          <span class="product-image-wrapper" style="padding-bottom: 125%;">
                            <img class="product-image-photo" src="<?php echo $imageUrl; ?>" max-width="240" max-height="300" alt="<?php echo $_item->getName(); ?>">
                          </span>
                        </span>
                      </a>
                      <div class="product-item-details">
                        <strong class="product-item-name">
                          <a title="<?php echo $_item->getName(); ?>" href="<?php echo $_item->getProductUrl(); ?>" class="product-item-link"><?php echo $_item->getName(); ?></a>
                        </strong>

                        <?php echo $block->getProductPrice($_item); ?>
                          <div class="product-item-inner">
                            <div class="product-item-actions">
                            <div class="actions-primary">
                             <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                             <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                              <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                              <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                              <?php echo $block->getBlockHtml('formkey')?>
                              <button type="submit"
                              title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                              class="action tocart primary">
                              <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                            </button>
                          </form>
                        </div>
                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                        <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist">
                          <span><?php echo __('Add to Wish List') ?></span>
                        </a>
                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <a href="#" class="action tocompare"
                        data-post='<?= /** @noEscape */ $compareHelper->getPostDataParams($_item); ?>'
                        data-role="add-to-links"
                        title="<?= /** @noEscape */ __('Add to Compare') ?>">
                        <span><?= /** @noEscape */ __('Add to Compare') ?></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
        <?php endforeach; ?>
      </ol>
    </div>
  </div>
</div>
<script type="text/x-magento-init">
{
  "[data-role=tocart-form], .form.map.checkout": {
    "catalogAddToCart": {
    "bindSubmit": true
    }
  },

  "*": {
    "Magento_Ui/js/core/app": {
      "components": {
        "wishlist": {
        "component": "Magento_Wishlist/js/view/wishlist"
        }
      }
    },
    "magepowRelated": {
    }
  }
}
</script>